---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Learning Group at Chi Hack Night

This repository contains all scripts written during [Chi Hack Night](https://chihacknight.org) in the [R Learning Group](https://github.com/chihacknight/breakout-groups/issues/173). We meet on **Tuesday nights at Merchandise Mart**, and I encourage you to come to a session! (There are great weekly speakers, but the breakout groups start around 7:30pm if you want to strategically time your arrival.) In any case, you can register for Chi Hack Night [here](https://www.eventbrite.com/e/chi-hack-night-registration-41703945624).

This group is currently organized by Angela Li, R Spatial Advocate at the [Center for Spatial Data Science](https://spatial.uchicago.edu) at UChicago. I also founded [R-Ladies Chicago](https://rladieschicago.org) and love R!

## Structure

In general, we start with a dataset found on the [Chicago Data Portal](https://data.cityofchicago.org/). We then import, manipulate, and visualize it using R. The focus is often on using the [`tidyverse`](https://www.tidyverse.org/) to teach a quick data workflow. Learn more about this suite of packages in the free [R for Data Science](https://r4ds.had.co.nz/) book.

## Contents

| Date | What we did | R Script |
|------------------------|------------------------|------------------------|
| 2019-01-22 | Import [Illinois Traffic Stop data metrics](https://d4q93323g8cmn.cloudfront.net/data/2017_metrics.csv) (mentioned in the night's talk, video [here](https://chihacknight.org/events/2019/01/22/racial-disparities-IL-traffic-stops.html)), check for missingness using `naniar`, select variables with `dplyr`| [2019-01-22_traffic-stops.R](https://github.com/angela-li/r-learning-group/blob/master/R/2019-01-22_traffic-stops.R) |
| 2019-01-08 | Look at [Chicago police stop data](https://home.chicagopolice.org/isr-data/), use `dplyr` to clean data and look at racial breakdowns of stops (statistic briefly mentioned in the night's talk on the Vote Equity project [here](https://chihacknight.org/events/2019/01/08/vote-equity-project.html)) | [2019-01-08_police-stops.R](https://github.com/angela-li/r-learning-group/blob/master/R/2019-01-08_police-stops.R) |
| 2018-12-11 | Import Chicago [fire station location data](https://data.cityofchicago.org/Administration-Finance/Current-Employee-Names-Salaries-and-Position-Title/xzkq-xp2w) as a GeoJSON with `sf` and make a `leaflet` map with it | [2018-12-11_firestations.R](https://github.com/angela-li/r-learning-group/blob/master/R/2018-12-11_firestations.R) |
| 2018-12-04 | Import [Chicago public salary data](https://data.cityofchicago.org/Administration-Finance/Current-Employee-Names-Salaries-and-Position-Title/xzkq-xp2w) with `RSocrata`, look at top salaries (in aggregate and by department) with `dplyr`, make a histogram of median salaries by department with `ggplot2` | [2018-12-04_salaries.R](https://github.com/angela-li/r-learning-group/blob/master/R/2018-12-04_salaries.R) |
| 2018-10-30 | Import [affordable housing data](https://data.cityofchicago.org/Community-Economic-Development/Affordable-Rental-Housing-Developments/s6ha-ppgi) (csv downloaded from Chicago Data Portal), do some basic data manipulation with `dplyr`, make a map with `leaflet` | [2018-10-30_housing.R](https://github.com/angela-li/r-learning-group/blob/master/R/2018-10-30_housing.R) |
| 2018-10-23 | Walked through the `starwars` dataset in `dplyr`, familiarized ourselves with RStudio and R, did some data manipulation, and made one or two plots in `ggplot2` | [2018-10-23_starwars.R](https://github.com/angela-li/r-learning-group/blob/master/R/2018-10-23_starwars.R) |


## Resources

- [Introductory slides for sessions](https://docs.google.com/presentation/d/1qEyoOjJx1elaftrCnckWGMjFZ7xZaGP4fsQeAp9Zp5c/edit#slide=id.g4632030f2f_0_0)
- [R for Data Science](https://spatial.uchicago.edu)
- [RStudio Cloud](https://rstudio.cloud)

## Contact Me
Have questions about R? Submit an issue in this repository or send me an email at ali6@uchicago.edu. Or reach out via Twitter @[CivicAngela](https://twitter.com/CivicAngela).
